import "@/app/globals.css";
import { Metadata } from "next";
import Navbar from "../layout/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Navbar/>
      <div className="bg-gray-200/60 dark:bg-neutral-950">
        {children}
      </div>
    </div>
  );
}
